export const FETCH_DOCTORS = 'FETCH_DOCTORS'
export const FETCH_DOCTOR = 'FETCH_DOCTOR'

export const TOGGLE_NOT_FOUND = 'TOGGLE_NOT_FOUND'
export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION'

export const ADD_BOOKING = 'ADD_BOOKING'